Update taxipp v20
fpagnoux/openfisca-core pull request #3
Opened 2017-11-22 11:10 UTC by fpagnoux

PR open for discussion

2017-11-22 11:12 UTC, fpagnoux commented on openfisca_core/formulas.py
> +        if variable.value_type in [float, int]:
@benjello ces vérifications de cohérences en sortie de calcul sont-ils à conserver ?

2017-11-22 13:10 UTC, fpagnoux commented on openfisca_core/holders.py
> +            self.value = value
@benjello je ne vois pas trop la différence de comportement introduite ici. Tu te souviens pourquoi ça a été fait ?

2017-11-22 13:14 UTC, fpagnoux commented on openfisca_core/holders.py
> +        hits_by_period[period] = (hits[0] + 1, hits[1] + 1 if array is None else hits[1])
@benjello quelle est la différence entre les deux éléments du tuple ? Lecture à gauche et écriture à droite ?

2017-11-22 13:21 UTC, benjello requested changes

2017-11-22 13:21 UTC, benjello commented on openfisca_core/formulas.py
> +        if variable.value_type in [float, int]:
Disons que je reconnais qu'il faudrait les virer mais que c'est souvent très utile pour déboguer quand on a des données.
Bref, preneur d'une solution élégante.

2017-11-22 13:21 UTC, benjello commented on openfisca_core/holders.py
> +            self.value = value
Gestion des scalaires mais je ne sais pas quel était le problème

2017-11-22 13:21 UTC, benjello commented on openfisca_core/holders.py
> +        hits_by_period[period] = (hits[0] + 1, hits[1] + 1 if array is None else hits[1])
Je ne me souviens pas mais on dirait que cela compte les calcul ou recalcul (=écriture chez toi) par exemple si on blackliste la variable. Je ne me souviens plus. @eraviart se souviens peut-être ?

2017-11-22 15:54 UTC, ClaireLeroyIPP commented
J'ai une question (je ne sais pas trop si c'est le bon endroit pour la poser) à propos de la commande openfisca-run-test, j'ai l'impression qu'elle ne marche plus dans *update-taxip-v20* alors qu'elle marchait dans *taxipp*.

Exemple : 
```
cleroy@pse-ipp-316-4 MINGW64 /c/GitHub/openfisca-core (update-taxipp-v20)
$ openfisca-run-test ../openfisca-france/tests/calculateur_impots aacc_defn.yaml
Traceback (most recent call last):
  File "C:\Python27\Scripts\openfisca-run-test-script.py", line 11, in <module>
    load_entry_point('OpenFisca-Core', 'console_scripts', 'openfisca-run-test')()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\github\openfisca-core\openfisca_core\scripts\run_test.py", line 8, in <module>
    from openfisca_core.tools.test_runner import run_tests
  File "c:\github\openfisca-core\openfisca_core\tools\test_runner.py", line 15, in <module>
    import nose
ImportError: No module named nose
```

2017-11-22 16:01 UTC, benjello commented
C'est une erreur d'import. Il ne trouve pas le paquet nose.
Tu as dû instalelr le paquet avec 
```
pip install -e .
```
Mais si tu veux lancer les tests il faut que tu l'installes avec l'option test 
```
pip install -e .[test]
``` 
afin que pip installe également 
les paquets nécessaires aux tests.
Tu peux voir cela dans le fichier [setup.py](https://github.com/openfisca/openfisca-france/blob/master/setup.py)

2017-12-01 17:25 UTC, fpagnoux commented on openfisca_core/formulas.py
> +        if variable.value_type in [float, int]:
On peut activer ces contrôles seulement en mode debug.

Par contre, ça veut dire qu'on instaure une nouvelle convention : une variable numérique ne doit pas renvoyer de valeur infinie.

2017-12-01 17:47 UTC, fpagnoux commented on openfisca_core/formulas.py
> +        if variable.value_type in [float, int]:
Hum, ça va plus loin que ça, vu qu'on instaure aussi un maximum de `1e9`, qui est sans doute pertinent pour la France, mais qui n'est peut-être pas généralisable partout... Je vais séparer ce morceau des autres, et on pourra en rediscuter dans une PR séparée.

2017-12-02 07:37 UTC, benjello commented on openfisca_core/formulas.py
> +        if variable.value_type in [float, int]:
Cela a servit surtout à déboguer. Afin de ne pas interférer avec le reste du code et pour des raisons de performance que penses-tu des propositions suivantes:
 - Avoir un debug mode qui vérifie que les valeurs sont inférieurs à une valeur qui peut être < infini
 - Limiter la vérification de finitude sera limité aux floats afin de ne pas avoir à le faire pour les âges ou avoir une white-list

2019-03-20 20:39 UTC, closed without merging